name: Run OpenSIPS Conformance Tests

on:
  # Triggers the workflow on all push or pull request events
  push:
  pull_request:

jobs:

  build:

    runs-on: ubuntu-latest

    steps:

    - name: Checkout SIPssert repo
      uses: actions/checkout@v3
      with:
        repository: 'OpenSIPS/SIPssert'
        path: sipssert

    - name: Install SIPssert
      working-directory: sipssert
      run: python3 setup.py install --user clean

    - name: Checkout Tests repo
      uses: actions/checkout@v3
      with:
        path: tests

    - name: Run All Tests
      working-directory: tests
      run: ./run-all.sh --test 01.record-route

    - name: Compress logs
      uses: a7ul/tar-action@v1.1.3
      with:
        cwd: tests
        command: c
        files: logs/latest
        outPath: sipssert-logs.tar.gz

    - name: Publish logs
      uses: actions/upload-artifact@v3
      if: always()
      with:
        name: sipssert-logs
        path: sipssert-logs.tar.gz
