name: Run OpenSIPS Conformance Tests

on:
  # Triggers the workflow on all push or pull request events
  push:
  pull_request:

jobs:

  build:

    runs-on: ubuntu-latest

    steps:

    - name: Checkout SIPssert repo
      uses: actions/checkout@v3
      with:
        repository: 'OpenSIPS/SIPssert'

    - name: Install SIPssert
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Checkout Tests repo
      uses: actions/checkout@v3

    - name: Execute Tests
      run: sipssert *

